export const BTP_CONFIG = {
  nom: "BTP Pro",
  slogan: "Gérez vos chantiers intelligemment",
  logo: "/assets/logo.png",
  couleurPrimaire: "#F59E0B",
  couleurSecondaire: "#0F172A",
  couleurAccent: "#F59E0B",
  adresse: "12 avenue des Bâtisseurs, 64000 Pau",
  ville: "Pau",
  codePostal: "64000",
  telephone: "05 59 00 00 00",
  email: "contact@btp-pro.fr",
  siret: "123 456 789 00010",
  siteWeb: "https://www.btp-pro.fr",
  tauxTVA: 0.20,
  margeParDefaut: 0.15,
  metiers: [
    "Plomberie",
    "Carrelage",
    "Électricité",
    "Maçonnerie",
    "Peinture",
    "Menuiserie",
    "Couverture",
    "Plâtrerie",
    "Chauffage",
    "Multi-corps",
  ],
  colonnesCRM: [
    "TOUS_PROSPECTS",
    "ENVOI_DEVIS",
    "RELANCE_1",
    "RELANCE_2",
    "RELANCE_3",
    "GAGNE",
    "PERDU",
  ],
  roles: [
    "Chef de chantier",
    "Ouvrier",
    "Commercial",
    "Administratif",
    "Gérant",
  ],
  statuts: [
    "En cours",
    "Terminé",
    "En attente",
    "Annulé",
  ],
  delaiRelanceJours: 3,
  validiteDevisJours: 30,
  prefixeDevis: "DEV-2026-",
  prefixeFacture: "FAC-2026-",
} as const;

export type BTPConfig = typeof BTP_CONFIG;
